/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/mountain_bike.glb --output src/components/MountainBike.jsx --types 
Author: Niilo Poutanen (https://sketchfab.com/niilo.poutanen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-bike-1d9270f82a34460e928709bbf7709d56
Title: Mountain bike
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_UV2_0: THREE.Mesh
    Cylinder001_UV6_0: THREE.Mesh
    Cylinder068_Shiny_Metal_0: THREE.Mesh
    Cylinder069_UV7_0: THREE.Mesh
    Cylinder070_Black_Plastic_0: THREE.Mesh
    Cylinder071_UV1_0: THREE.Mesh
    Plane_Black_Plastic_0: THREE.Mesh
    pCube121_Black_Plastic_0: THREE.Mesh
    pCylinder791_Black_Metal_0: THREE.Mesh
    pCylinder827_Shiny_Metal_0: THREE.Mesh
    pCylinder971_Black_Plastic_0: THREE.Mesh
    pCube137_Black_Plastic_0: THREE.Mesh
    Cylinder072_Black_Metal_0: THREE.Mesh
    Cylinder072_Black_Plastic_0: THREE.Mesh
    Circle_Shiny_Metal_0: THREE.Mesh
    Circle001_Black_Metal_0: THREE.Mesh
    Cylinder073_Black_Metal_0: THREE.Mesh
    Circle002_Rim_0: THREE.Mesh
    Circle002_Black_Metal_0: THREE.Mesh
    Mtb_Wheel_Tire_0: THREE.Mesh
    Cylinder002_Grip_0: THREE.Mesh
    Cylinder003_Grip_0: THREE.Mesh
    Shimano_SLX_M675_Black_Metal_0: THREE.Mesh
    Shimano_SLX_M675_Shiny_Metal_0: THREE.Mesh
    Circle003_Shifter_0: THREE.Mesh
    Circle003_Black_Plastic_0: THREE.Mesh
    ['Hayes_Mag_9_-_Disk_Brake_Caliper_Black_Metal_0']: THREE.Mesh
    ['Hayes_Mag_9_-_Disk_Brake_Caliper_Black_Plastic_0']: THREE.Mesh
    ['Hayes_Mag_9_-_Disk_Brake_Caliper001_Black_Metal_0']: THREE.Mesh
    ['Hayes_Mag_9_-_Disk_Brake_Caliper001_Shiny_Metal_0']: THREE.Mesh
    BezierCurve_Black_Plastic_0: THREE.Mesh
    Mtb_Wheel001_Tire_0: THREE.Mesh
    Circle005_Rim_0: THREE.Mesh
    Circle005_Black_Metal_0: THREE.Mesh
    BezierCurve001_Black_Plastic_0: THREE.Mesh
    Cube_Black_Plastic_0: THREE.Mesh
    Cube001_Black_Plastic_0: THREE.Mesh
    BezierCurve002_Black_Plastic_0: THREE.Mesh
    Cube004_Black_Metal_0: THREE.Mesh
    Cube005_Black_Metal_0: THREE.Mesh
    Circle006_Black_Metal_0: THREE.Mesh
    Circle006_Black_Plastic_0: THREE.Mesh
    Circle006_Orange_0: THREE.Mesh
    Circle006_UV8_0: THREE.Mesh
    BezierCurve003_Black_Plastic_0: THREE.Mesh
    Plane001_Shiny_Metal_0: THREE.Mesh
    Plane001_Metal_0: THREE.Mesh
    Plane001_Black_Metal_0: THREE.Mesh
    group_6_Shiny_Metal_0: THREE.Mesh
    group_6_Shiny_Metal_0_1: THREE.Mesh
    group_6_Shiny_Metal_0_2: THREE.Mesh
    Cube002_Metal_0: THREE.Mesh
    Cube003_Black_Metal_0: THREE.Mesh
    Circle004_Shiny_Metal_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshPhysicalMaterial
    material_1: THREE.MeshPhysicalMaterial
    Shiny_Metal: THREE.MeshStandardMaterial
    material_3: THREE.MeshPhysicalMaterial
    Black_Plastic: THREE.MeshStandardMaterial
    material_5: THREE.MeshPhysicalMaterial
    Black_Metal: THREE.MeshPhysicalMaterial
    material_7: THREE.MeshStandardMaterial
    Tire: THREE.MeshStandardMaterial
    Grip: THREE.MeshStandardMaterial
    Shifter: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    material_12: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/mountain_bike.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[49.254, 31.047, 0]} rotation={[-Math.PI / 2, -0.395, 0]} scale={2.515}>
            <mesh geometry={nodes.Cylinder072_Black_Metal_0.geometry} material={materials.Black_Metal} />
            <mesh geometry={nodes.Cylinder072_Black_Plastic_0.geometry} material={materials.Black_Plastic} />
          </group>
          <group position={[-76.772, -26.296, 0.503]} scale={40.908}>
            <mesh geometry={nodes.Circle002_Rim_0.geometry} material={materials.material_7} />
            <mesh geometry={nodes.Circle002_Black_Metal_0.geometry} material={materials.Black_Metal} />
          </group>
          <group position={[44.949, 61.8, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.089}>
            <mesh geometry={nodes.Shimano_SLX_M675_Black_Metal_0.geometry} material={materials.Black_Metal} />
            <mesh geometry={nodes.Shimano_SLX_M675_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} />
          </group>
          <group position={[44.949, 61.8, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Circle003_Shifter_0.geometry} material={materials.Shifter} />
            <mesh geometry={nodes.Circle003_Black_Plastic_0.geometry} material={materials.Black_Plastic} />
          </group>
          <group position={[63.889, -26.052, -5.312]} rotation={[-Math.PI, 0, 2.796]} scale={1.131}>
            <mesh geometry={nodes['Hayes_Mag_9_-_Disk_Brake_Caliper_Black_Metal_0'].geometry} material={materials.Black_Metal} />
            <mesh geometry={nodes['Hayes_Mag_9_-_Disk_Brake_Caliper_Black_Plastic_0'].geometry} material={materials.Black_Plastic} />
          </group>
          <group position={[-63.617, -26.793, -6.994]} rotation={[-Math.PI, 0, -1.188]} scale={1.427}>
            <mesh geometry={nodes['Hayes_Mag_9_-_Disk_Brake_Caliper001_Black_Metal_0'].geometry} material={materials.Black_Metal} />
            <mesh geometry={nodes['Hayes_Mag_9_-_Disk_Brake_Caliper001_Shiny_Metal_0'].geometry} material={materials.Shiny_Metal} />
          </group>
          <group position={[74.537, -26.349, 9.367]} scale={40.908}>
            <mesh geometry={nodes.Circle005_Rim_0.geometry} material={materials.material_7} />
            <mesh geometry={nodes.Circle005_Black_Metal_0.geometry} material={materials.Black_Metal} />
          </group>
          <group position={[-12.781, -32.723, 8.073]} scale={[4.482, 4.482, 5.691]}>
            <mesh geometry={nodes.Circle006_Black_Metal_0.geometry} material={materials.Black_Metal} />
            <mesh geometry={nodes.Circle006_Black_Plastic_0.geometry} material={materials.Black_Plastic} />
            <mesh geometry={nodes.Circle006_Orange_0.geometry} material={materials.Orange} />
            <mesh geometry={nodes.Circle006_UV8_0.geometry} material={materials.material_12} />
          </group>
          <group position={[-71.016, -47.697, -4.702]} rotation={[-Math.PI / 2, -0.159, 0]} scale={25.127}>
            <mesh geometry={nodes.Plane001_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} />
            <mesh geometry={nodes.Plane001_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Plane001_Black_Metal_0.geometry} material={materials.Black_Metal} />
          </group>
          <group position={[212.322, -49.749, 7.282]} scale={3.36}>
            <mesh geometry={nodes.group_6_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} />
            <mesh geometry={nodes.group_6_Shiny_Metal_0_1.geometry} material={materials.Shiny_Metal} />
            <mesh geometry={nodes.group_6_Shiny_Metal_0_2.geometry} material={materials.Shiny_Metal} />
          </group>
          <mesh geometry={nodes.Cylinder_UV2_0.geometry} material={materials.material} position={[34.979, 46.002, 0]} rotation={[-Math.PI / 2, 1.103, 0]} scale={2.732} />
          <mesh geometry={nodes.Cylinder001_UV6_0.geometry} material={materials.material_1} position={[109.442, -1.1, 0]} rotation={[-Math.PI / 2, -0.378, 0]} scale={3.17} />
          <mesh geometry={nodes.Cylinder068_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} position={[55.852, 14.766, 0]} rotation={[-Math.PI / 2, -0.387, 0]} scale={1.926} />
          <mesh geometry={nodes.Cylinder069_UV7_0.geometry} material={materials.material_3} position={[-44.642, 2.125, 0]} rotation={[-Math.PI / 2, 0.903, 0]} scale={1.402} />
          <mesh geometry={nodes.Cylinder070_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[39.247, 49.416, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder071_UV1_0.geometry} material={materials.material_5} position={[39.517, 60.167, 0]} rotation={[-Math.PI / 2, 1.16, 0]} scale={2.222} />
          <mesh geometry={nodes.Plane_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[-32.517, 60.544, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.pCube121_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[-41.044, 51.084, -0.007]} rotation={[0, 0, 0.283]} scale={6.414} />
          <mesh geometry={nodes.pCylinder791_Black_Metal_0.geometry} material={materials.Black_Metal} position={[-45.799, 55.139, -2.281]} rotation={[0, 0, -1.427]} scale={[0.492, 9.166, 0.408]} />
          <mesh geometry={nodes.pCylinder827_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} position={[-44.815, 52.841, -3.09]} rotation={[Math.PI / 2, 0, 0]} scale={0.56} />
          <mesh geometry={nodes.pCylinder971_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[-32.94, 24.151, 0.117]} rotation={[0, 0, 0.282]} scale={[2.52, 1.06, 2.35]} />
          <mesh geometry={nodes.pCube137_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[-32.65, 24.432, 3.518]} rotation={[0.073, -0.241, 0.298]} scale={[8.169, 1.893, 0.627]} />
          <mesh geometry={nodes.Circle_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} position={[75.065, -26.313, -4.969]} scale={8.822} />
          <mesh geometry={nodes.Circle001_Black_Metal_0.geometry} material={materials.Black_Metal} position={[-74.726, -26.601, 6.883]} scale={1.476} />
          <mesh geometry={nodes.Cylinder073_Black_Metal_0.geometry} material={materials.Black_Metal} position={[43.398, 63.386, 0]} scale={4.596} />
          <mesh geometry={nodes.Mtb_Wheel_Tire_0.geometry} material={materials.Tire} position={[74.688, -25.979, 0.477]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={1.248} />
          <mesh geometry={nodes.Cylinder002_Grip_0.geometry} material={materials.Grip} position={[40.522, 61.975, 44.301]} rotation={[-Math.PI, 0.076, -1.373]} scale={[-1.555, 1.555, 1.555]} />
          <mesh geometry={nodes.Cylinder003_Grip_0.geometry} material={materials.Grip} position={[41.247, 61.975, -34.945]} rotation={[-Math.PI, -0.066, -1.373]} scale={[-1.555, 1.555, 1.555]} />
          <mesh geometry={nodes.BezierCurve_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[44.949, 61.8, 0]} rotation={[-1.614, -0.1, 1.566]} scale={39.836} />
          <mesh geometry={nodes.Mtb_Wheel001_Tire_0.geometry} material={materials.Tire} position={[-75.442, -26.312, 0.477]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={1.248} />
          <mesh geometry={nodes.BezierCurve001_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[76.398, -26.368, 0.152]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Cube_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[12.2, 0.621, 0.152]} rotation={[-Math.PI / 2, 0.522, Math.PI]} scale={[-0.367, 1.483, 0.662]} />
          <mesh geometry={nodes.Cube001_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[32.043, 31.049, 0.152]} rotation={[-Math.PI / 2, 0.789, Math.PI]} scale={[-0.367, 1.483, 0.662]} />
          <mesh geometry={nodes.BezierCurve002_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[77.542, -26.368, 0.037]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Cube004_Black_Metal_0.geometry} material={materials.Black_Metal} position={[74.814, -25.452, -9.769]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.424, 0.108, 0.424]} />
          <mesh geometry={nodes.Cube005_Black_Metal_0.geometry} material={materials.Black_Metal} position={[-75.242, -26.034, -12.335]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.424, 0.108, 0.424]} />
          <mesh geometry={nodes.BezierCurve003_Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[-14.654, -25.164, 25.104]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Cube002_Metal_0.geometry} material={materials.Metal} position={[-22.098, -22.609, 8.972]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube003_Black_Metal_0.geometry} material={materials.Black_Metal} position={[-18.221, -20.619, 7.017]} rotation={[-Math.PI / 2, 0, 0]} scale={0.557} />
          <mesh geometry={nodes.Circle004_Shiny_Metal_0.geometry} material={materials.Shiny_Metal} position={[-75.466, -26.313, -4.969]} scale={8.822} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mountain_bike.glb')
